import Nav from "@/components/layout/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Climate_Crisis } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/context/AuthContext";
import localFont from '@next/font/local'
// const inter = Inter({ subsets: ["latin"] });
const climate_Crisis = Climate_Crisis({ subsets: ["latin"] });
const polysans = localFont({
  src: [
    {
      path: '../../public/fonts/PolySansBulky.ttf',
      weight: '800'
    },  
  ],
  variable: '--font-polysans'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={climate_Crisis.className}>
        <AuthProvider>
          <Nav />
          {children}
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
