import "./globals.css";
import type { Metadata } from "next";
import { Climate_Crisis } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
const climate_Crisis = Climate_Crisis({ subsets: ["latin"] }); 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={climate_Crisis.className}>{children}</body>
    </html>
  );
}
